// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/nonya123456/deckpath/internal/manager"
	"github.com/nonya123456/deckpath/internal/prompt"
)

// Injectors from wire.go:

func InitializeContainer() *Container {
	reader := prompt.ProvideReader()
	cliManager := manager.ProvideCLIManager(reader)
	container := &Container{
		Manager: cliManager,
	}
	return container
}
