// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/nonya123456/deckpath/internal/prompt"
)

// Injectors from wire.go:

func InitializeContainer() *Container {
	reader := prompt.ProvideReader()
	container := &Container{
		PromptReader: reader,
	}
	return container
}
